### ISSUE TITLE
activeFxOnHover doesn't work

### ISSUE THREAD

**Issue by aisha0926** [bonarja/react-glitch-image#2]
Animation triggers even after adding the hover props

**Comment by bonarja** [comment]
[Release v1.2.2](https://github.com/bonarja/react-glitch-image/releases/tag/v1.2.2)

## 🔥 Bug fix
- FIX:  filter effects were not activated on mouseover
- FIX: pauses the animation interval when mousehovering and restarts the interval when mouseleaving


If you wish to have the activator only onmousehover

```javascript
<GlitchImage
   image='image.jpg' 
   activeFxOnHover={true}
   activeFxOnInterval={false}
/>
```
