### ISSUE TITLE
Not working on Newer React versions.

### ISSUE THREAD

**Issue by sameert89** [bonarja/react-glitch-image#3]
Installing the package causes dependency errors:

```
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: react-glitch-image@1.2.2
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!     react-glitch-image@"^1.2.2" from the root project
npm ERR!
```
The install works with --legacy-peer-deps, but it is not good in the long run.

**Comment by bonarja** [comment]
New version [v1.3.0](https://github.com/bonarja/react-glitch-image/releases/tag/v1.3.0) for react 18.

Thanks for reporting.
